config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events, except: [:destroy] do
  resources :registrations, only: [:create]
  end
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :photos
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  def bargain?
    price < 30
  end

  def self.order_by_price
    order :price
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  MAX_REGISTRATION_NUMBER= 4

  has_many :events
  has_one :profile
  has_many :registrations, dependent: :destroy
  has_many :booked_events, through: :registrations, source: :event

  def full_name
    return profile.full_name if profile?

    email
  end

  def profile?
    profile.present? && profile.persisted?
  end

  def guest_count?
    if guest_count <= MAX_REGISTRATION_NUMBER
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end
      redirect_to @event, notice: "Event succesfully created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You do not have permission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to @event, notice: "Event updated"
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(event_params)

    @event.destroy

    redirect_to events_path
  end

  private

  def image_params
    params[:images].present? ? params.require(:images) : []
  end


  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
    .require(:event)
    .permit(
      :name, :location, :price, :capacity, :active, :description, :starts_at, :ends_at, :includes_foods, :includes_drinks, :user_id, category_ids: []
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event= photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :bio)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_event

    def create
      @registration= current_user.registrations.create(registration_params.merge({
       event:  @event }))

      redirect_to @registration.event, notice: "Thank you for your registration!"
    end

    private

    def registration_params
      params.require(:registration).permit(:status, :guests_count)
    end

    def load_event
      @event = Event.find(params[:event_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>


<div class="form-group">
  <label>Event name</label>
  <%= f.text_field :name, placeholder: "Event name", class: "form-control" %>
</div>

<div class="form-group">
  <label>Location</label>
  <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
</div>

<div class="form-group">
  <label>Start Date</label>
  <%= f.date_field :starts_at, placeholder: "Start Date", class: "form-control" %>
</div>

<div class="form-group">
  <label>End Date</label>
  <%= f.date_field :ends_at, placeholder: "End Date", class: "form-control" %>
</div>


<div class="form-group">
  <label>Capacity</label>
  <%= f.number_field :capacity, placeholder: "Capacity", class: "form-control" %>
</div>

<label>Extra Information</label>

<div class="form-group">
  <%= f.check_box :includes_foods %> Include Food
</div>

<div class="form-group">
  <%= f.check_box :includes_drinks %> Include Drinks
</div>

<label>Categories</label>

<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
<div class="form-group">
  <%= b.check_box(class: "check_box") %> <%= b.object.name %>
</div>
<% end %>

<div class="form-group">
  <label>Nightly Price</label>
  <div class="input-group">
    <div class="input-group-addon">€</div>
    <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
  </div>
</div>

<label>Photos</label>

<div class="form-group">
  <span class="btn btn-default">
    Upload Photos
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </span>
</div>

<div id="photos">
  <%= render 'photos/list' %>
</div>

<label>Publish this event?</label>

<div class="form-group">
  <%= f.check_box :active %> Active
</div>

<div class="actions">
  <%= f.submit "Save", class: "btn btn-primary" %>
</div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Payed Events", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>Location: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Price: <%= @event.price %></p>
    <p>Capacity: <%= @event.capacity %></p>
    <p>Starting Date: <%= @event.starts_at %></p>
    <p>End Date: <%= @event.ends_at %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Amenities -->
    <h4>Extra information</h4>
    <ul class="ExtraInfo">
      <li><%= !@event.includes_foods ? ("<s>Food for Free</s>").html_safe : "Food for Free" %></li>
      <li><%= !@event.includes_drinks ? ("<s>Drinks for Free</s>").html_safe : "Drinks for Free" %></li>
    </ul>
  </div>

  <h4>Photos</h4>
  <% @event.photos.each do |photo| %>
  <%= image_tag photo.image.thumbnail %>
  <% end %>

  <h4>Categories</h4>
  <% @categories.each do |category| %>
  <span class="label label-success"><%= category.name %></span>
  <% end %>
</div>


<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codaisseurup</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <div class="col-sm-12 header-image">
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <div class="header-title">
        <h1>Awesome Events</h1>
      </div>
      <br>
      <div class="header-subtitle">
        <h5>Look at our amazing events you can join!</h5>
      </div>
      <br>
      <button class="btn btn-success btn-lg">View Events</button>
    </div>
  </div>

  <%= yield %>


  <footer class="footer">
    <div class="container">
      <span class="text-muted"> 	&#169; 2018- Anissa Codaisseurup.</span>
    </div>
  </footer>

</body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="col-sm-12 latest-events">
    <h1>Latest events</h1>
    <p class="latest-sub">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Aliquam lacinia, diam et pharetra congue, est felis bibendum nibh, ac placerat tellus odio eu nunc.
    </p>
  </div>
  <div class="row">
    <div class="col-md-4">
      <img src="/images/yoga.jpg" />
      <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
        pain..."</p>
      </div>
    </div>
    <div class="col-md-4">
      <img src="/images/books.jpg" />
      <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
        pain..."</p>
      </div>
    </div>
    <div class="col-md-4">
      <img src="/images/karate.jpg" />
      <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
        pain..."</p>
      </div>
    </div>
  </div>
</div>

<div class="full-width-container">
  <div class="container">
    <h2>Find an event</h2>
    <input type="text" name="search"/>
    <input type="submit" class="btn btn-default" value="Find"/>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-12 Categories">
      <h1>Explore</h1>
      <p class="latest-sub">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Aliquam lacinia, diam et pharetra congue, est felis bibendum nibh, ac placerat tellus odio eu nunc.
      </p>
    </div>
  </div>
  <div class="col-md-4">
    <img src="/images/sportsandfitness.jpg" />
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Sports and Fitness</h1>
    </div>
  </div>
  <div class="col-md-4 ">
    <img src="/images/outdoorsandadventures.jpg" />
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Outdoors and Adventures</h1>
    </div>
  </div>
  <div class="col-md-4 ">
    <img src="/images/tech.jpg" />
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Tech</h1>
    </div>
  </div>
  <div class="col-md-4 ">
    <img src="/images/writing.jpg" />
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Writing</h1>
    </div>
  </div>
  <div class="col-md-4">
    <img src="/images/music.jpg"/>
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Music</h1>
    </div>
  </div>
  <div class="col-md-4 ">
    <img src="/images/film.png" />
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Film</h1>
    </div>
  </div>
  <div class="col-md-4 ">
    <img src="/images/family.jpg" />
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Family</h1>
    </div>
  </div>
  <div class="col-md-4 ">
    <img src="/images/foodanddrinks.jpg" />
    <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
      pain..."</p>
      <h1>Food and Drinks</h1>
    </div>
  </div>
  <div class="container all-events">
    <h3>Thousand of events happening at any time</h3>
  </div>
</div>
</div>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= image_tag photo.image.thumbnail %>
    </div>
    <div class="panel-body">
      <%= link_to "Delete", photo_path(photo.id), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
<% @profile.errors.full_messages.each do |msg| %>
<p class="alert alert-danger"><%= msg %></p>
<% end %>

<div class="form-group">
  <label>First Name</label>
  <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
</div>

<div class="form-group">
  <label>Last Name</label>
  <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
</div>

<div class="form-group">
  <label>Bio</label>
  <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
</div>

<div class="actions">
  <%= f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Back", root_path, class: "btn btn-default" %>
</div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-static-top header-menu">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.full_name %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Your Events", events_path %></li>
              <li role="separator" class="divider"></li>

              <% if current_user.profile? %>
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>

          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>